# Generated by Django 5.2.13 on 2026-04-24 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('device_type', models.CharField(max_length=50)),
                ('os', models.CharField(max_length=50)),
                ('browser', models.CharField(max_length=50)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('qr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='qr.qrcode')),
            ],
        ),
    ]
