# Generated by Django 5.2.13 on 2026-05-05 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrscan',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
