# Generated by Django 5.2.13 on 2026-05-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_qrscan_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrscan',
            name='lattitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qrscan',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
