# Generated by Django 5.2.13 on 2026-05-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_qrscan_lattitude_qrscan_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrscan',
            old_name='lattitude',
            new_name='accuracy',
        ),
        migrations.AddField(
            model_name='qrscan',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
