# Generated by Django 5.2.13 on 2026-04-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='campaign',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
