# Generated by Django 5.2.13 on 2026-05-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0002_qrcode_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
