# Generated by Django 5.2.13 on 2026-05-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0003_qrcode_latitude_qrcode_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
